# Generated by Django 3.1.4 on 2021-01-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_1', models.IntegerField()),
                ('numero_2', models.IntegerField()),
                ('operadores', models.IntegerField(choices=[(1, '/'), (2, '*'), (3, '+'), (4, '-')])),
                ('resultado', models.IntegerField()),
            ],
            options={
                'db_table': 'calculadora',
            },
        ),
    ]
