# Generated by Django 3.1.4 on 2021-01-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_binaria', '0002_auto_20210112_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculadora',
            name='resultado',
            field=models.IntegerField(null=True),
        ),
    ]
