# Generated by Django 3.1.4 on 2021-01-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora_binaria', '0003_auto_20210112_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculadora',
            name='numero_1',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calculadora',
            name='numero_2',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calculadora',
            name='resultado',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
